title: Mike McMillan
email: portfolio@mikemcmillan.dev
description: >- 
  A dedicated engineer with over 10 years’ hands-on experience developing reliable, 
  high-performing, n-tier applications. Has had a career primarily focused on 
  backend development, but is keen to branch out and become full-stack.
baseurl: "" 
url: "" 
twitter_username: jekyllrb
github_username:  mcmillanmichael
theme: jekyll-theme-slate
plugins:
  - jekyll-feed